services:
  nextjs:   
    build:
        context: .
        dockerfile: ./build/nextjs/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-nextjs'
    restart: unless-stopped
    entrypoint: 'bash -c "npm install --no-package-lock && npm run dev"'
    volumes:
      - ./src/frontend:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - fortune-network
    ports:
       - 3000:3000 
  fastapi:   
    build:
        context: .
        dockerfile: ./build/fastapi/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-fastapi'
    restart: unless-stopped
    volumes:
      - ./src/backend:/home/code
    networks:
      - fortune-network
    ports:
       - 8000:80 

  postgres:
    image: postgres:15-alpine
    container_name: '${COMPOSE_PROJECT_NAME}-postgres'
    restart: always
    environment:
      POSTGRES_USER: admin@admin.com
      POSTGRES_PASSWORD: password
      POSTGRES_DB: larvahub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fortune-network
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: '${COMPOSE_PROJECT_NAME}-pgadmin'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - fortune-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      

      

 
volumes:
  postgres_data:
  pgadmin_data:
  node_modules: 

networks:
  fortune-network:
  
 
